### ISSUE TITLE
Create python specific mailing list

### ISSUE THREAD

**Issue by jclark754** [Unidata/python-general#3]
We are currently working on providing a lot of resources for our python community and it would be excellent to have a specific mailer to keep them updated. I've sent an email to Jen about creating one and will update here as it progresses.

**Comment by jclark754** [comment]
Per Jen, our mailing list is good to go. I think we should just use it to announce our projects, solicit contributions, etc.. Likely not a list for discussions (I set the list to moderated so replies need to be approved). If anything, it enables us to directly message interested parties about our python activities; it's another avenue for advertising what's happening as we try to advance python in the meteorological community and at Unidata.

**Comment by ddirks** [comment]
I assume we'll want to publicize this new list at some point. That might
tie in with an article about Unidata's python activities in general . . . I
know Ryan is thinking about another MetPy blog post, but should we expand
that into something more general? (That's a question, not a suggestion,
btw.)

-=DD=-

On Mon, Jul 6, 2015 at 11:18 AM, Joshua Clark <notifications@github.com>
wrote:

> Per Jen, our mailing list is good to go. I think we should just use it to
> announce our projects, solicit contributions, etc.. Likely not a list for
> discussions (I set the list to moderated so replies need to be approved).
> If anything, it enables us to directly message interested parties about our
> python activities; it's another avenue for advertising what's happening as
> we try to advance python in the meteorological community and at Unidata.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/python-general/issues/3#issuecomment-118928947>
> .
>



-- 
Douglas Dirks
Unidata Community Services
ddirks@unidata.ucar.edu  *  303-497-8657
